zuul:
  routes:
    app:
      serviceId: app-service
      path: /app/**
    app1:
      serviceId: app1-service
      path: /app1/**
    app2:
      serviceId: app2-service
      path: /app2/**

app-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8451,localhost:8452
    #IsSecured: true

app1-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8451
    #IsSecured: true

app2-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8452
    #IsSecured: true

