spring:
  application:
    name: API Demo Server
    env: Local

server:
  port: 8451
  ssl:
    enabled: true
    key-alias: app
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: apppass

security:
  require-ssl: true

